### ISSUE TITLE
how can i change @timestamp Time zone

### ISSUE THREAD

**Issue by jol5** [markmcdowell/NLog.Targets.ElasticSearch#118]
Thanks you code!

**Comment by markmcdowell** [comment]
Have you taken a look at https://github.com/NLog/NLog/wiki/Time-Source

**Comment by jol5** [comment]
> Have you taken a look at https://github.com/NLog/NLog/wiki/Time-Source

thanks ！
but i have some quetion  
 1. @timestamp es mapping is date:
![image](https://user-images.githubusercontent.com/28615922/77036609-7d14cb80-69ea-11ea-92a2-0211e0fee7bc.png)
![image](https://user-images.githubusercontent.com/28615922/77036664-9cabf400-69ea-11ea-879a-03c551d3edf5.png)
i hope kibana display GTM ;

2. i add a date filed,but es mapping is text instead of date :
 <field name="timestamp" layout="${longdate}" />

**Comment by jol5** [comment]
> > Have you taken a look at https://github.com/NLog/NLog/wiki/Time-Source
> 
> thanks ！
> but i have a quetion
> 
> 1. @timestamp es mapping is date:
>    ![image](https://user-images.githubusercontent.com/28615922/77036609-7d14cb80-69ea-11ea-92a2-0211e0fee7bc.png)
>    ![image](https://user-images.githubusercontent.com/28615922/77036664-9cabf400-69ea-11ea-879a-03c551d3edf5.png)
>    i hope kibana display GTM ;

ok，i got it！
just like that：
![image](https://user-images.githubusercontent.com/28615922/77048685-ccb2c180-6a01-11ea-9605-c3e1629b9be6.png)
