### ISSUE TITLE
Multiple Elasticsearch Target Urls

### ISSUE THREAD

**Issue by hmlmartins** [markmcdowell/NLog.Targets.ElasticSearch#120]
Hello,

This more of a question than an actual issue, but I could not find anywhere else to present this doubt I am having.

Given the possibility to have multiple elasticsearch urls in nlog config, how are these managed? It will always send requests to both targets? will it detect if the node is available, and forward to the first available node? will it balance between node urls?

Thank you,

**Comment by markmcdowell** [comment]
Hi if you specify multiple urls, it'll use a [Static Connection Pool](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/connection-pooling.html#static-connection-pool) that will ping the nodes to make sure they're healthy. It can issue requests against any healthy node.

**Comment by hmlmartins** [comment]
Thank you for your reply. Should be enough to get me going and to understand how to "balance" connections to our cluster.
