### ISSUE TITLE
Consider allowing to optionally use Elastic.CommonSchema.NLog.EcsLayout for providing Elastic Common Schema support

### ISSUE THREAD

**Issue by xprzemekw** [markmcdowell/NLog.Targets.ElasticSearch#122]
Hi,

It looks Elastic as a part of Elastic Common Schema ('ECS') effort introduced NLog support in form of specialized NLog Layout (named 'EcsLayout') that renders _LogEventInfo_ structure to proper JSON representation (as per ECS definition) which is ready to be submitted to Elastic via their Elastic Low Level Client (check https://github.com/elastic/ecs-dotnet/tree/master/src/Elastic.CommonSchema.NLog and https://github.com/elastic/ecs-dotnet/tree/master/src/Elastic.CommonSchema).

Can this be considered as a proper way of supporting ECS in NLog.Targets.ElasticSearch?

It seems we would need just a pass through option where _RenderLogEvent(Layout, logEvent)_ output is just sent to Elastic (assuming Layout is properly set to EcsLayout).

**Comment by snakefoot** [comment]
The library is still BETA-stage:

https://github.com/elastic/ecs-dotnet/pull/65

But yes when the API can be considered stable, then it would make sense to inject pure Json into the LowLevel-Client. 

Please make a PR that can take the output from the Target.Layout and pass as raw Json to the LowLevel-Client. Then you can use this Target together with [Elastic.CommonSchema.NLog](https://www.nuget.org/packages/Elastic.CommonSchema.NLog/) right now.

**Comment by snakefoot** [comment]
@xprzemekw Have created #125 that allows you to use JsonLayout (or EcsLayout) for generating document-payload. (

**Comment by snakefoot** [comment]
@markmcdowell When #125 has been released, then this issue can be resolved.

**Comment by markmcdowell** [comment]
Closed by #125 thanks to @snakefoot

**Comment by snakefoot** [comment]
Remember to update release notes for 7.3.0 about change in default DocumentType from logevent to _doc


Sent from my Sony Xperia


---- Mark McDowell wrote ----


Closed by #125<https://github.com/markmcdowell/NLog.Targets.ElasticSearch/pull/125> thanks to @snakefoot<https://github.com/snakefoot>
