### ISSUE TITLE
Writing to data stream in elastic returns an error

### ISSUE THREAD

**Issue by hmlmartins** [markmcdowell/NLog.Targets.ElasticSearch#132]
Hello,

I set up my index to be a data stream in elastic but I get an error stating the request should have op_type: create.

Is there a way to overcome, or is this not ready yet to work with data streams?

Thank you

**Comment by snakefoot** [comment]
@hmlmartins You can try this pre-release [nuget-package](https://ci.appveyor.com/api/buildjobs/nws831ap6fnwg1pt/artifacts/src%2FNLog.Targets.ElasticSearch%2Fbin%2FRelease%2FNLog.Targets.ElasticSearch.7.1.20-alpha-bamrajut.nupkg) to see if resolves your problem (Just place in local nuget-folder).

It introduces a new option called `OpCodeCreate` that can be used like this:

```xml
<target xsi:type="ElasticSearch" uri="http://localhost:9200/" opCodeCreate="true" />
```

**Comment by hmlmartins** [comment]
unfortunately the lib version we are using comes bundled with another
software tool we have in place.

I will have to wait for them to update. Is it possible to get notice of
when it is no longer pre-release?

Thanks

**Comment by snakefoot** [comment]
Sadly enough it will stay pre-release until someone validates it is working.


So maybe create a small test tool that depends on the provided pre-release nuget-package. And do a quick test?


Sent from my Sony Xperia


---- hmlmartins wrote ----


unfortunately the lib version we are using comes bundled with another
software tool we have in place.

I will have to wait for them to update. Is it possible to get notice of
when it is no longer pre-release?

Thanks

**Comment by hmlmartins** [comment]
Thanks for the feedback

We have a small dev environment, maybe I will be able to test it. Not
really sure when. Best estimate at the moment is the end of year. But I'll
keep an eye out for changes and eventually provide some feedback.

Regards,

**Comment by snakefoot** [comment]
> But I'll keep an eye out for changes and eventually provide some feedback.

Excellent. Looking forward to hear about the test results.

**Comment by TheDruidsKeeper** [comment]
I ran into this issue as well, so I took the time to test the PR build and it worked perfectly for me. I'm using elastic v7.9.1, and verified with the prelease package that I could still write to traditional (non data stream) indexes both with & without `opCodeCreate="true"`. Writing to the datastream isn't successful without the opCodeCreate enabled (as expected), and is successful with it.

**Comment by snakefoot** [comment]
ElasticSearch ver. 7.5.0 has been released: https://www.nuget.org/packages/NLog.Targets.ElasticSearch
