### ISSUE TITLE
How to use ApiKeyAuthenticationCredentials?

### ISSUE THREAD

**Issue by EddLonzanida** [markmcdowell/NLog.Targets.ElasticSearch#135]
Is there an option where i can use cloudId with id and apiKey? I'm hoping there is.

**Comment by EddLonzanida** [comment]
I've created a pull request for this. https://github.com/markmcdowell/NLog.Targets.ElasticSearch/pull/147

**Comment by snakefoot** [comment]
@markmcdowell This issue can now be resolved. NLog.Targets.ElasticSearch .ver 7.6.0 includes the options `ApiKeyId` + `ApiKey` for use with `ApiKeyAuthenticationCredentials`.
