### ISSUE TITLE
Add support for ignore_malformed

### ISSUE THREAD

**Issue by Sirozha1337** [markmcdowell/NLog.Targets.ElasticSearch#137]
Please add support of `ignore_malformed` option. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-malformed.html

**Comment by snakefoot** [comment]
If you know how to do this with [Elasticsearch.Net - ElasticLowLevelClient](https://www.nuget.org/packages/Elasticsearch.Net/) then please create pull-request.
