### ISSUE TITLE
Exclude default fields (@timestamp, level, message)

### ISSUE THREAD

**Issue by ShujaARizvi** [markmcdowell/NLog.Targets.ElasticSearch#138]
I want to use my own fields for timestamp, level, and message. But the default fields make my data redundant. Need to exclude these default fields but not sure how to.

**Comment by snakefoot** [comment]
You can use `enableJsonLayout="true"` to provide you own custom JsonPayload. See also #125

**Comment by EddLonzanida** [comment]
Check out this pull request: https://github.com/markmcdowell/NLog.Targets.ElasticSearch/pull/147
