### ISSUE TITLE
What is the behavior when the  target Elasticsearch host is down or unreachable?

### ISSUE THREAD

**Issue by mshwf** [markmcdowell/NLog.Targets.ElasticSearch#151]
Hi,
We are comparing using Filebeat and NLog.Target.Elasticsearch to send logs to Elasticsearch, in case Elasticsearch is hosted on a different machine.
Will NLog.Target.Elasticsearch retry sending logs generated when Elasticsearch service was offline or the machine is down? so I don't lose logs if ES machine is not reachable?

**Comment by markmcdowell** [comment]
You can use the RetryingTargetWrapper to keep trying when it errors but I would use Filebeat where you can.

**Comment by mshwf** [comment]
Thanks for the quick reply, appreciate your help!
