### ISSUE TITLE
Requesting new NuGet build for full API id/key authentication support

### ISSUE THREAD

**Issue by Robin-Clemens** [markmcdowell/NLog.Targets.ElasticSearch#153]
Hello,

Currently I am facing an issue with API id+key authentication, by looking at the code it looks like this library fully supports that feature. However, as it turns out, this feature is not yet completely available in the latest NuGet package (v7.6.0)

That build is from June, which added API id/key authentication support **in combination** with a Cloud ID, it wasn't till a month later that support was added API id/key authentication without Cloud ID support [https://github.com/markmcdowell/NLog.Targets.ElasticSearch/commit/9ac0286ab1ff11738244ac54b45ee644089cf512](https://github.com/markmcdowell/NLog.Targets.ElasticSearch/commit/9ac0286ab1ff11738244ac54b45ee644089cf512)

However, no new NuGet package was created after that commit, meaning that the latest version in NuGet doesn't actually fully support this feature just yet. (Not unless you are using a Cloud ID, which we are not as we are hosting on-prem.)

Therefor, I am requesting a NuGet build of the latest code so this gets fully added.
(Option 2 would be cloning the code and rolling my own, but I would rather not unless I really have to.)

Note: I did test it locally by cloning the code and building it myself, and then it works properly, so the issue is just the outdated NuGet package. Once that is updated I can just grab the package from there.

**Comment by snakefoot** [comment]
Guess we are waiting for @markmcdowell

**Comment by snakefoot** [comment]
@markmcdowell Polite poke for new build to be released.

**Comment by markmcdowell** [comment]
Tagged, should build and publish a new release

**Comment by markmcdowell** [comment]
Available in v7.7.0
