### ISSUE TITLE
Could not load file or assembly 'System.Diagnostics.DiagnosticSource

### ISSUE THREAD

**Issue by tsfinley** [markmcdowell/NLog.Targets.ElasticSearch#155]
Got this after installing the nuget package:

System.IO.FileLoadException: 'Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

Info: .NET 4.8, NLog 4.7.14

**Comment by smriti2901** [comment]
You can install specific version as a Nuget package and specify assembly binding in your web.config

`<dependentAssembly>
<assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="CC7B13FFCD2DDD51" culture="neutral"/
<bindingRedirect oldVersion="0.0.0.0-6.0.0.1" newVersion="6.0.0.1"/>
</dependentAssembly>`
