### ISSUE TITLE
Does not work with NLog.Web.AspNetCore 5

### ISSUE THREAD

**Issue by venca-x** [markmcdowell/NLog.Targets.ElasticSearch#161]
After upgrade to NLog.Web.AspNetCore 5, does not work

**Comment by snakefoot** [comment]
If you are using `enableJsonLayout="true"` then you are waiting for this bug-fix: https://github.com/markmcdowell/NLog.Targets.ElasticSearch/pull/159 (The workaround while waiting for the bug-fix to be released is to explicit assign `pipeline=""`).

If not using  `enableJsonLayout="true"`, then you should enable [NLog Internal Logging](https://github.com/NLog/NLog/wiki/Internal-Logging) and look for warnings and errors.

**Comment by snakefoot** [comment]
Notice NLog 5 also includes the breaking change [NLog Extensions assemblies will not load automatically](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#nlog-extensions-assemblies-will-not-load-automatically)

So you explicit specify the extension in NLog.config:
```xml
  <extensions>
    <add assembly="NLog.Targets.ElasticSearch"/>
  </extensions>
```

See also https://github.com/markmcdowell/NLog.Targets.ElasticSearch

Alternative you can include the extension-assembly-name in the target-type-alias.
