### ISSUE TITLE
Invalid xsi:type 'http://www.nlog-project.org/schemas/NLog.xsd:ElasticSearch'

### ISSUE THREAD

**Issue by LinchaiTheShinigami** [markmcdowell/NLog.Targets.ElasticSearch#162]
On my Visual Studio Editor I get a warning.

This is an invalid xsi:type 'http://www.nlog-project.org/schemas/NLog.xsd:ElasticSearch'.	

Which impacts on a line with the format below:

`<target xsi:type="ElasticSearch" layout="${logger} | ${threadid} | ${message}" >`

I provide a schema location:

`<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd http://www.nlog-project.org/schemas/NLog.xsd">`

Is there an alternative xsd file to reference to or am I doing something wrong?

**Comment by snakefoot** [comment]
Do not think anyone has made a XSD-Schema for the ElasticTarget. The easy way of getting rid of the warning is changing `xsi:type="ElasticSearch"` to `type="ElasticSearch"`
