### ISSUE TITLE
Support NLog 5

### ISSUE THREAD

**Issue by paladinu** [markmcdowell/NLog.Targets.ElasticSearch#163]
Is there a plan to support NLog 5?  The readme shows this:

Version | Elasticsearch Version | NLog Version
-- | -- | --
7.x | 7.x | 4.6.x
6.x | 6.x | 4.5.x

But no mention of version 5.  I'm just trying to plan updates and wondering if I'm locked in.

**Comment by snakefoot** [comment]
NLog 5.0 is already supported.

But if using `EnableJsonLayout` then you have to explicitly specify `pipeline=""` until #159 has been merged and released.

**Comment by paladinu** [comment]
Great news!  Thank you!

**Comment by rgueldenpfennig** [comment]
I can confirm that. The workaround is working fine so far.

- .NET 6
- NLog 5.0.4
- NLog.Targets.ElasticSearch 7.7.0
- Elasticsearch 8.3.3
