### ISSUE TITLE
Send logs to elastic cloud datastream

### ISSUE THREAD

**Issue by Mehdi-MAMOU** [markmcdowell/NLog.Targets.ElasticSearch#177]
Hello,

I'm trying to send logs to a data stream on my elastic cloud deployment through an index template.
Here is my nlog configuration : 
<target name="elastic" xsi:type="ElasticSearch"
				index="emailapi-dev"
				opCodeCreate="create"
				cloudId=""
				includeAllProperties="true"
				requireAuth="true"
				apiKey=""
				apiKeyId=""
				documentType=""
				layout="${longdate}|${level:uppercase=true}|thread=${threadname:whenEmpty=${threadid}}|${callsite}|${message} ${exception:format=tostring}"
				pipeline="emailapi">

This doesn't write to the data stream created. Here is my index template configuration : 
![image](https://github.com/markmcdowell/NLog.Targets.ElasticSearch/assets/143518327/a5df83c8-479b-40e8-b01e-7ec9da457ffa)

Can someone help me please ?

Best Regards,
Mehdi MAMOU

**Comment by snakefoot** [comment]
Have you tried to explictly specify `opCodeCreate="true"`:
```xml
<target xsi:type="ElasticSearch" uri="http://localhost:9200/" opCodeCreate="true" />
```
See also #132

Always a good idea to check the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) for clues, when having to troubleshoot logging with NLog

**Comment by Mehdi-MAMOU** [comment]
Hi,

Thanks for your help. It works now.

Indeed, it was an ugly mistake from my part.

Best Regards,
Mehdi MAMOU
