### ISSUE TITLE
Thrown exception is not sent to Elasticsearch

### ISSUE THREAD

**Issue by akunaatrium** [markmcdowell/NLog.Targets.ElasticSearch#43]
Logging such exception works:
`_logger.Debug(new Exception("error"), "This exception is logged");`

Sample code that does not send the log event to Elasticsearch:

```
try
{
	System.IO.File.Open(@"C:\nonexisting.txt", System.IO.FileMode.Open);
}
catch (Exception ex)
{
	_logger.Debug(ex, "This exception is NOT logged");
}
```

In both cases the `_logger` is `LogManager.GetCurrentClassLogger();`.

In the non-working case, when monitoring the HTTP traffic, the Elasticsearch API endpoint is not even called, so the block must be somewhere before the HTTP request is done.

Using NLog.Targets.ElasticSearch version 4.0.0-beta21.

**Comment by markmcdowell** [comment]
I'm struggling to see why they would be any different....

I'll see if I can reproduce.

**Comment by markmcdowell** [comment]
Closing as stale, this may be already fixed since i'm assuming something in the exception was causing a circular reference in the json.
