### ISSUE TITLE
Log not written in Elasticsearch

### ISSUE THREAD

**Issue by feelit** [markmcdowell/NLog.Targets.ElasticSearch#60]
Dear all,
I'm trying to get working the NLog with target to Elasticsearch in my asp.net web API application.
The .net framework version of my application is 4.6.
I'm using Elasticsearch, Nest and Elasticsearch.NET V. 5.6.
NLog.Targets.ElasticSearch V 3.0.0
NLog 4.4.3

Following is my NLog.config

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog"/>
  </configSections>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
        autoReload="true"
        throwExceptions="true"
        throwConfigExceptions="true"
        internalLogLevel="Off"
        internalLogFile="c:\temp\nlog-internal.log">
  <extensions>
    <add assembly="NLog.Targets.ElasticSearch"/>
  </extensions>
  <targets>
    <target 
          name="logfile" 
          xsi:type="File" 
          fileName="Nlog.txt" />

    <target name="elastic"
              xsi:type="BufferingWrapper"
              bufferSize="1"
              flushTimeout="1">
      <target xsi:type="ElasticSearch"
              layout="${logger} | ${threadid} | ${message}"
              index="test-log-${date:format=yyyy.MM.dd}"
              includeAllProperties="true"
              uri="http://###.###.###.###:9200/">

        <field name="user"
               layout="${windows-identity:userName=True:domain=False}"/>
        <field name="host"
               layout="${machinename}"/>
      </target>
    </target>    
  </targets>

  <rules>
    <logger enabled="true" name="*" minlevel="Debug" writeTo="logfile" />
    <logger enabled="true" name="*" minlevel="Debug" writeTo="elastic" />
  </rules>
</nlog>
</configuration>
```

In the API I have a method for testing the log entry.

```
private static NLog.Logger _logger = NLog.LogManager.GetCurrentClassLogger();

        [AllowAnonymous]
        [HttpGet]
        public HttpResponseMessage Hello()
        {
            _logger.Info("Hello World!!!!!!!!!!!!");
            _logger.Trace("Sample trace message");
            _logger.Debug("Sample debug message");
            _logger.Info("Sample informational message");
            _logger.Warn("Sample warning message");
            _logger.Error("Sample error message");
            _logger.Fatal("Sample fatal error message");
            return Request.CreateResponse(HttpStatusCode.OK, "Hello World!");
        }
```

I can see the Log entry in the Nlog.txt file but nothing in Elasticsearch.
I downloaded the NLog.Targets.ElasticSearch project and attached to my application in order to debug it.
Debugging it, I can see in the following code

```
private void SendBatch(ICollection<AsyncLogEventInfo> events)
        {
            try
            {
                var logEvents = events.Select(e => e.LogEvent);

                var payload = FormPayload(logEvents);

                var result = _client.Bulk<byte[]>(payload);

                if (!result.Success)
```

that result.Seccess is equal true.
So no exceptions, but I don't se the log index to be created.
The web API already works properly with Elasticsearch.

Can someone help me to understand what is wrong? Did I miss something?
Thanks in advance for your time.

**Comment by markmcdowell** [comment]
Do you see any errors in elasticsearch?

Does the index already exist? If not do you have action.auto_create_index turned off in elasticsearch?

**Comment by feelit** [comment]
I don't see any errors in elasticsearch.
The index does not exist.
In my nodes config I have the following settings:

`action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*`

Is it correct? Do I need to change it? Should I add in that list `test-log-*`

**Comment by olcay** [comment]
Hi @feelit,

I think everything looks fine. Just try to update NLog.Targets.ElasticSearch to v4.
I had same issue without any clue so I updated NLog.Targets.ElasticSearch to v5 for Elasticsearch v6.

Since you have Elasticsearch.NET V. 5.6, you need to use NLog.Targets.ElasticSearch v4.

**Comment by AlexanderNaiden** [comment]
@markmcdowell . Do we need previously create indexes in ES before we start push logs into ES? Because my code works, it pushes logs into ES but for looking at saved logs I need to create indexes into ES.

**Comment by AlexanderNaiden** [comment]
> 
> 
> @AlexanderNaiden no you don't but this is dependant on your elasticsearch settings. The default value changed between versions of elasticsearch as well. See
> https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-creation

Maybe index was created but Kibana shows next message (I probably need ask about index pattern): 
You only have a single index. You can create an index pattern to match it.
testapp-log-2019.01.22
--

**Comment by markmcdowell** [comment]
it sounds like your kibana setting is wrong, check your index pattern is using a wildcard. e.g. `testapp-log-*`

**Comment by AlexanderNaiden** [comment]
@markmcdowell  I've created public repo and push there my spike which titled as `Test NLog.Targets interaction with ElasticSearch` -> https://github.com/AlexanderNaiden/NLogTargetsWithES. In my solution it needs to create index pattern in kibana manually (maybe it's the only way to use ES with NLog.Targets). We are gonna to use NLog.Targets with ES in our project.

**Comment by markmcdowell** [comment]
Ah sorry, in Kibana you always have to manually add the index pattern. 

The NLog target will write the index and data to Elasticsearch. Kibana configuration is separate from this, all you're doing is configuring Kibana to add the data.

**Comment by markmcdowell** [comment]
@feelit sorry I missed your question, yes `action.auto_create_index` would need to include the index pattern.
