### ISSUE TITLE
Log not written documentType change

### ISSUE THREAD

**Issue by cddldg** [markmcdowell/NLog.Targets.ElasticSearch#66]
For the first time：
target like ：
```
index="agentservice" 
documentType="app" 
```
Write successful.
The second time:
target like ：
```
index="agentservice" 
documentType="job"
```
Write failed .
My Elasticsearch version "6.3.0"。

Q：
What should I do if I want to write different type

**Comment by markmcdowell** [comment]
documentType is deprecated by elasticsearch, you can no longer have different types in an index.
