### ISSUE TITLE
Parameter pipeline not supported on ElasticSearchTarget

### ISSUE THREAD

**Issue by timblackwell** [markmcdowell/NLog.Targets.ElasticSearch#68]
When defining an Elasticsearch Target to use a pipeline, I get the exception: `Parameter pipeline not supported on ElasticSearchTarget`
Example config:
```
      <target name="elastic"
              type="ElasticSearch"
              index="logs-test-${date:format=yyyy.MM.dd}"
              connectionStringName="ElasticsearchUrl"
              pipeline="test-pipeline">
```

**Comment by markmcdowell** [comment]
Yeah that's a weird one, I don't remember it ever being a property but it was on the wiki page.

I've removed it from the wiki page.

**Comment by markmcdowell** [comment]
Ah yes, I reverted the commit because it broke the target for versions without pipeline support.

**Comment by timblackwell** [comment]
Ah okay. Hmm would be really nice if it was.
What are your thoughts on brining it back but just documenting this is only for elasticsearch version > 5?
