### ISSUE TITLE
Bulk insert success on read only index

### ISSUE THREAD

**Issue by ada3000** [markmcdowell/NLog.Targets.ElasticSearch#79]
Elasticsearch move index to read only mode when free space is low.
NLog.Targets.ElasticSearch "successefully" insert new items, but in elasticsearch index no new documents.
https://discuss.elastic.co/t/forbidden-12-index-read-only-allow-delete-api/110282

**Comment by markmcdowell** [comment]
We rely on the elasticsearch api for posting to the node, I'm assuming that is returning success. Could you try using [v6.0.0](https://github.com/markmcdowell/NLog.Targets.ElasticSearch/releases/tag/6.0.0) to see if they have resolved it in a newer version of the api.
