### ISSUE TITLE
Read password from environment

### ISSUE THREAD

**Issue by Baklap4** [markmcdowell/NLog.Targets.ElasticSearch#80]
While trying to connect to Elastic cloud we now have to supply a username and password. Since the Uri parameter can be read from the environment using `${environment:SOME_ENV_HOST}` i thought why not do the same with password. However this seems not to work because when sending the `/_bulk` the decoded auth header is the following: `some_user:${environment:SOME_ENV_PASS}` this obviously does not authenticate correctly with Elastic cloud resulting in an unauthorized...

**Comment by markmcdowell** [comment]
Yes, currently we're only passing in username and password if specified in config. It would make sense to allow environment variables though. Possibly ES_USER, ES_PASSWORD,...

**Comment by snakefoot** [comment]
Created PR #84

**Comment by snakefoot** [comment]
Ver. 6.1.0 has been released: https://www.nuget.org/packages/NLog.Targets.ElasticSearch
