### ISSUE TITLE
Target.index not written to kibana & logs arrived in multilines

### ISSUE THREAD

**Issue by rong0312** [markmcdowell/NLog.Targets.ElasticSearch#82]
Hey all,
I am newbie with this solution so forgive me..
However, i cant tell why my logs get indexed with the default option of target.index and didnt take
my chosen index:

```
 <targets>

    <target name="elastic" xsi:type="BufferingWrapper" flushTimeout="5000">
    <target xsi:type="ElasticSearch"  
            name="logstash"
            uri="http://elk-dev.wsldevops.com:5000"
            index="NLog-${date:format=yyyy.MM.dd}"
            documentType="NLog"
            includeAllProperties="True">

    </target>
    </target>
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="elastic" />
  </rules>
```

The results in Kibana:

![screen shot 2019-01-24 at 16 35 59](https://user-images.githubusercontent.com/33253167/51685132-56315400-1ff6-11e9-978b-4aa462592a3b.png)

Please notice the log (6 lines instead of 1?) and the index.
What did i miss?

**Comment by rong0312** [comment]
Nothing there against http://elk-dev.wsldevops.com:5000/NLog-*

I have checked the index management aswell, only logstash-* comes in.

**Comment by aheubusch** [comment]
Tested your config on my machine and its working.
The index got lower cased to `nlog-2019.01.29`. Try the link again with `/nlog-*` or even `/*` (that will return all indices on the server). Alternatively `/_cat/indices?v` also returns a list of all indices.

Your rule specifies `minLevel="Info"`. Is it possible that you only log Trace or Debug?

**Comment by rong0312** [comment]
Thank you very much guys for the answers,
Currently i moved to NLog's Network output (TCP) to send log, testing it right now.
You are right, a painful take away is that index has to be lower cased!!! (i didnt know that)

Thank you again for your time guys
