### ISSUE TITLE
Version conflict when including in a netcoreapp2.1 project

### ISSUE THREAD

**Issue by lipmas** [markmcdowell/NLog.Targets.ElasticSearch#85]
Im trying to include latest version 6.1.0 in a project using target framework netcoreapp2.1 which also includes the [Microsoft.AspNetCore.App](https://www.nuget.org/packages/Microsoft.AspNetCore.App/2.1.8) . There is however a version conflict and i get this error when trying to build the project

```
error NU1107: Version conflict detected for Microsoft.Extensions.Configuration. Install/reference Microsoft.Extensions.Configuration 2.2.0 directly to project to resolve this issue.
error NU1107:  Corvus-hub -> NLog.Targets.ElasticSearch 6.1.0 -> Microsoft.Extensions.Configuration.Json 2.2.0 -> Microsoft.Extensions.Configuration (>= 2.2.0)
error NU1107:  Corvus-hub -> Microsoft.AspNetCore.App 2.1.8 -> Microsoft.Extensions.Configuration (>= 2.1.1 && < 2.2.0).
```

Are there any work-arounds for this issue? I would really like to be able to include the latest 6.1.0 version from nuget. In my testing with version 5.1 i've noticed a lot of logs are dropped but upgrading to 6.1 seems to have fixed the issues.

**Comment by markmcdowell** [comment]
You just need to add a binding redirect to the version of configuration you’re using.

See https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

**Comment by snakefoot** [comment]
> Binding redirects are a .NET framework concept, there are no binding redirects on .NET Standard and .NET Core:

https://stackoverflow.com/a/46120907

**Comment by markmcdowell** [comment]
I was sure you could do an equivalent and just add the dependency as a package reference in your app...

**Comment by lipmas** [comment]
@markmcdowell @snakefoot Thanks a lot for your responses and help. 

Unfortunately I was not able to get binding redirects working and im not sure if there is an equivalent for overriding assembly dependencies in .NET core. It may also just be a limitation of the [Microsoft.AspNetCore meta package](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.1) which seems like it prevents 3rd party packages from changing the version of of packages included in Microsoft.AspNetCore.App.

It could be that im missing something obvious but i havent been able to get around this issue without changing the `NLog.Targets.ElasticSearch` project directly.

What about @snakefoot idea of changing the .netstandard2.0 target framework to include `<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.1.0" />` so downgrading  to version 2.1 because its the LTS version. It doesnt seem like version 2.2 is a strict requirement for this project ?

**Comment by snakefoot** [comment]
> It doesnt seem like version 2.2 is a strict requirement for this project?

Nope. Actually the future plan is to remove the dependency completely.

**Comment by snakefoot** [comment]
@markmcdowell Guess this issue can be resolved with ver. 7.0 (No longer depends on Microsoft.Extensions.Configuration.Json). See also #97
