### ISSUE TITLE
Upgrade to use ElasticSearch 7.0.0

### ISSUE THREAD

**Issue by ultimaustin** [markmcdowell/NLog.Targets.ElasticSearch#95]
Hi, I've made some local changes to upgrade this package to use version 7.0.0 of  ElasticSearch.Net (which requires updating the dependencies to minimum .Net 4.7.2). Would I be able to commit this change to a branch for consideration?

**Comment by markmcdowell** [comment]
Sure, we'd just bump the major version.

**Comment by ultimaustin** [comment]
Cool. It looks like I don't have rights to check in a new branch or changes to master. Whats the preferred mechanism to submit a change?

**Comment by markmcdowell** [comment]
You fork the repo to your local, create a branch and then submit a pull request with your changes. 

See https://guides.github.com/activities/forking/
