### ISSUE TITLE
StackOverflowException raised when logging object which has self-referencing loop field

### ISSUE THREAD

**Issue by lhyqy5** [markmcdowell/NLog.Targets.ElasticSearch#99]
When logging a self-referencing loop object, the program just aborted with a message '_Process is terminating due to StackOverflowException_'.

It's seems caused by serializing in `ElasticSearch.Net.PostData`

I found there is an `ElasticsearchSerializer` property in target config, I wonder know how can I config this property to use my custom Serializer in the `nlog` config file.

**Comment by snakefoot** [comment]
ReferenceLoopHandling  is configured:

https://github.com/markmcdowell/NLog.Targets.ElasticSearch/blob/0e78f96d3f5b4b5890d92b7c2ef24da601ec15ef/src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs#L271

**Comment by lhyqy5** [comment]
this config does not affect  Elasticsearch's default serializer `Elasticsearch.Net.LowLevelRequestResponseSerializer` which use `Elasticsearch.Net.SimpleJson`

**Comment by snakefoot** [comment]
Looks like SimpleJson is being replaced https://github.com/elastic/elasticsearch-net/pull/3608

**Comment by snakefoot** [comment]
If you are very good, then you can setup dependency-injection with NLog, so when NLog loads the nlog.config, then you can override the creation of the ElasticSearchTarget-object (and assign your custom implementation of IElasticsearchSerializer):

```c#
var defaultConstructor = NLog.Config.ConfigurationItemFactory.Default.CreateInstance;
NLog.Config.ConfigurationItemFactory.Default.CreateInstance.CreateInstance = type =>
{
   if (type == typeof(ElasticSearchTarget))
       return new ElasticSearchTarget() { ElasticsearchSerializer = myFunkySerializer };
   
   return defaultConstructor(type);
};
```
https://github.com/NLog/NLog/wiki/Dependency-injection-with-NLog

Just make sure to setup the factory-logic before loading the NLog-config. Or perform a reload of the NLog-config after having setup the factory-logic.

**Comment by lhyqy5** [comment]
I have tried your solution, it works well, Thanks.
